version: 2
registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/crookm/index.json
    username: crookm
    password: ${{ secrets.GITHUB_TOKEN }}

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - github
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
