name: reporting

on:
  workflow_run:
    workflows: [ ci ]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results

      - name: build unit test view
        uses: dorny/test-reporter@v1
        with:
          name: unit test report
          path: "**/*.trx"
          reporter: dotnet-trx

      - name: build coverage view
        uses: 5monkeys/cobertura-action@master
        with:
          path: "**/*.xml"
          minimum_coverage: 75
